# Site
name: "Best Puckin' Hockey Podcast Blog"
title: "Best Puckin' Hockey Podcast Blog"
description: "The official blog of TBPHP where we log our crazy theories, predictions, and ramblings."
logo: 'assets/images/tbphp_logo_notext.png'
# baseurl: /
# google_analytics: ''
disqus: 'tbphp'
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kyle:
    name: Kyle
    display_name: Kyle
    gravatar: 4f6fb9dd5019b779f54d8c47441f1d28
    email: bestpuckin@gmail.com
    web: https://bestpuckin.com
    twitter: https://twitter.com/bestpuckin
    description: "Host and editor for The Best Puckin' Hockey podcast. St. Louis Blues and Toronto Maple Leafs fan."
  jon:
    name: Jon
    display_name: Jon    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: bestpuckin@gmail.com
    web: https://bestpuckin.com
    twitter: https://twitter.com/bestpuckin
    description: "Host of The Best Puckin' Podcast. Carolina Hurricanes and New Jersey Devils fan."
  austin:
    name: Austin
    display_name: Austin    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: bestpuckin@gmail.com
    web: https://bestpuckin.com
    twitter: https://twitter.com/bestpuckin
    description: "Host of The Best Puckin' Podcast. St. Louis Blues and Columbus Blue Jackets fan."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
